### PR TITLE
Made speaker section  Responsive 

### PR DESCRIPTION
**Pull request by mahesh-11102**
# `Before`
image

# `After`
image

### CODE REVIEW

**Comment by gvssaimadhav** [comment]
Mahesh, Please Make it look Center Alligned!

**Comment by kode-logger** [comment]
@mahesh-11102 The page is not responsive.
image
Even removing the margin doesn't fix it.
The better fix will be to use media queries.

**Comment by mahesh-11102** [comment]
sure @gvssaimadhav and @kode-logger  I'll working with `media queries` thanks for guiding me 😃

**Comment by mahesh-11102** [comment]
## I have fixed the Speaker issue,

> Here I'm sharing the SS of my work
image

image
image
image

**Comment by kode-logger** [comment]
# Updated Speaker page

## Changes Made:
- Discarded old card animation.
- Discarded previous card styles.

## New/Updated Features:
- Added new card style.
- Added new animation to the cards.
- Supports mobile views.

Fixes #59
Fixed by @mahesh-11102 
Changes approved by @kode-logger

**Pull request merged**
